### ISSUE TITLE
Getting More Detailed exception errors

### ISSUE THREAD

**Issue by creekg** [DinoChiesa/Edge-Powershell-Admin#8]
I'm not getting full error details in the Exception

eg 
$deploy = Deploy-EdgeApi -Name $edgeapiname -Env $apigeeenvironmentname -Revision $Revision -ErrorAction Stop

if I catch an exception ($_.Exception|format-list -force) I can retrieve the error message 'The Remote server returned an error: (400) Bad Request

however if I execute

Deploy-EdgeApi -Name $edgeapiname -Env $apigeeenvironmentname -Revision $Revision -ErrorAction Stop

I will get then get the full detailed error displayed on screen

PS. Thanks for this Module, Great Work :)

**Comment by DinoChiesa** [comment]
I think maybe you want to catch the exception, then examine
$_.Errordetails.message

Is that what you want?

**Comment by creekg** [comment]
Hi DinoChiesa

Thanks, that helps :)

$ErrorMessage = $_.Errordetails.Message
$FailedItem = $ErrorMessage | ConvertFrom-Json | Select-Object -expand cause | foreach {$_.message}

**Comment by DinoChiesa** [comment]
Great, glad to hear it.  I'll close this off now.
